// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package entity

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Brand struct {
	BrandID     pgtype.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
	Name        string
	Description string
}

type Category struct {
	CategoryID  pgtype.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
	ParentID    pgtype.UUID
	Name        string
	Description string
}

type Product struct {
	ProductID   pgtype.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
	BrandID     pgtype.UUID
	CategoryID  pgtype.UUID
	ShopID      pgtype.UUID
	Name        string
	Sku         pgtype.Text
	Description pgtype.Text
	IsActive    bool
	Status      int32
}

type ProductImage struct {
	ImageID   pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
	ProductID pgtype.UUID
	VariantID pgtype.UUID
	ImageUrl  string
	IsPrimary bool
}
