// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package entity

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Brand struct {
	ID          uuid.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
	Name        string
	Description string
}

type Category struct {
	ID          uuid.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
	ParentID    *uuid.UUID
	Name        string
	Description string
}

type Product struct {
	ID          uuid.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
	BrandID     *uuid.UUID
	CategoryID  *uuid.UUID
	ShopID      *uuid.UUID
	Name        pgtype.Text
	Sku         pgtype.Text
	Description pgtype.Text
	IsActive    pgtype.Bool
	Status      pgtype.Int4
}

type ProductImage struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
	ProductID uuid.UUID
	VariantID *uuid.UUID
	ImageUrl  string
	IsPrimary bool
}
