// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  product_id, name, sku, description
) VALUES (
  $1, $2, $3, $4
)
RETURNING product_id
`

type CreateProductParams struct {
	ProductID   pgtype.UUID
	Name        string
	Sku         pgtype.Text
	Description pgtype.Text
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ProductID,
		arg.Name,
		arg.Sku,
		arg.Description,
	)
	var product_id pgtype.UUID
	err := row.Scan(&product_id)
	return product_id, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE product_id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, productID)
	return err
}

const getDetailProduct = `-- name: GetDetailProduct :one
SELECT product_id, created_at, updated_at, deleted_at, brand_id, category_id, shop_id, name, sku, description, is_active, status FROM products
WHERE product_id = $1 LIMIT 1
`

func (q *Queries) GetDetailProduct(ctx context.Context, productID pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getDetailProduct, productID)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.BrandID,
		&i.CategoryID,
		&i.ShopID,
		&i.Name,
		&i.Sku,
		&i.Description,
		&i.IsActive,
		&i.Status,
	)
	return i, err
}

const getListProduct = `-- name: GetListProduct :many
SELECT product_id, created_at, updated_at, deleted_at, brand_id, category_id, shop_id, name, sku, description, is_active, status FROM products
LIMIT $1 OFFSET $2
`

type GetListProductParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetListProduct(ctx context.Context, arg GetListProductParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, getListProduct, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ProductID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.BrandID,
			&i.CategoryID,
			&i.ShopID,
			&i.Name,
			&i.Sku,
			&i.Description,
			&i.IsActive,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
  set name = $2
WHERE product_id = $1
`

type UpdateProductParams struct {
	ProductID pgtype.UUID
	Name      string
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct, arg.ProductID, arg.Name)
	return err
}
